name: k2traveliq
description: A service intervention planning and guidance app for technicians
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  uuid: ^4.3.3
  path_provider: ^2.1.1
  speech_to_text: ^7.3.0
  docx_template: ^0.3.3
  file_selector: ^1.0.1
  pdf: ^3.10.7
  printing: ^5.13.3
  archive: ^3.3.0
  open_file: ^3.2.1
  share_plus: ^12.0.1
  file_picker: ^10.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  msix: ^3.16.8
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
